whitelists:
  office:
    ips:
      - 192.168.1.0/24
      - 10.0.0.0/8
  home:
    ips:
      - 203.0.113.5/32
  cdn-edge:
    url: https://edge-ips.example.com

ingressAssignments:
  - name: my-app-ingress
    namespace: default
    whitelist: office
  - name: another-ingress
    namespace: prod
    whitelist: home
  - namespace: staging
    whitelist: cdn-edge